import Head from "next/head";
import { useState } from "react";
import Header from "../components/Header";
import SidePanel from "../components/SidePanel";

export default function Home() {
  const [isPanelOpen, setIsPanelOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col">
        <Header setIsPanelOpen={setIsPanelOpen} />
        <SidePanel isPanelOpen={isPanelOpen} />
      </div>
    </div>
  );
}
